name: Pack and Publish to Github Packages

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Add Github Packages as Nuget Source
      run: dotnet nuget add source --username ${{ secrets.GH_USERNAME }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/diegodalben/index.json"
        
    - name: Pack All Projects
      run: dotnet pack ./PublishNugetGalery_PoC.sln --output packages --configuration Release
    
    - name: Push to Nuget Gallery
      #run: dotnet nuget push "packages/*.nupkg" --source "https://nuget.pkg.github.com/diegodalben/index.json" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
      run: dotnet nuget push "packages/*.nupkg" --source "github" --skip-duplicate
