name: Pack and Publish to Github Packages

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Pack All Projects
      run: dotnet pack ./PublishNugetGalery_PoC.sln --output packages --configuration Release
      
    - name: Set Nuget Source
      run: dotnet nuget add source --username diegodalben --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://github.com/diegodalben/publish_nuget_gallery_poc/packages"
    
    - name: Push to Nuget Gallery
      run: dotnet nuget push "packages/*.nupkg" --source "github" --skip-duplicate
